@startuml
left to right direction

actor "Workspace Admin" as WorkspaceAdmin
actor User
actor "Workspace Member" as WorkspaceMember
actor "Board Owner" as BoardOwner
actor "Workspace Visitor" as WorkspaceVisitor

rectangle "User Management" {
  usecase "Login" as UC112
  usecase "Manage Profil" as UC113
}
User --> UC112
User --> UC113

rectangle "Workspace Management" as Workspace_Management{
  usecase "Invite user to Workspace" as UC107
  usecase "Delete Workspace" as UC108
  usecase "Invite as Visitor" as UC114
  usecase "Invite as Member" as UC115
  usecase "Manage Workspace" as UC110
}
WorkspaceAdmin --> UC108
WorkspaceAdmin --> UC107
WorkspaceAdmin --> UC110
UC107 <|-- UC114
UC107 <|-- UC115

rectangle "Board Management" as Boad_Management{
  usecase "Create and Update board" as UC101
  usecase "Edit board column" as UC102
  usecase "Populate the board" as UC103
  usecase "Change View" as UC104
  usecase "Communicate by comments" as UC105
  usecase "Manage Board Permissions" as UC106
  usecase "Read Board" as UC116
  usecase "Delete board" as UC117
}
WorkspaceMember <|-right- BoardOwner
WorkspaceVisitor <|-right- WorkspaceMember
WorkspaceMember --> UC101
WorkspaceMember --> UC103
WorkspaceMember --> UC102
WorkspaceMember --> UC104
WorkspaceMember --> UC105
BoardOwner --> UC106
BoardOwner --> UC117
WorkspaceVisitor --> UC116

@enduml